config/routes.rb
WhatsupMontreal::Application.routes.draw do

  get "user/account"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  match "/user" => "user#account"

  root to: 'pages#home'

  resource :assets

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.oauth_token ||= auth["credentials"]["token"]
      user.oauth_expires_at ||= Time.at(auth["credentials"]["expires_at"])
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Never Bored MTL" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">Never Bored</a>
          <div class="container-fluid">
            <ul class="nav">
              <li><%= link_to "Venues", "/path1"  %></li>
              <li><%= link_to "Artists", "/path2"  %></li>
              <li><%= link_to "Events", "/path3"  %></li>
            </ul>
            <ul class="nav pull-right">
              <% if !current_user.nil? then %>
                <li id="fat-menu" class="dropdown">
                  <a classs ="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %>
                    <b class="caret" style="color: grey"></b>
                  </a>
                  <ul class ="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li><%= link_to "Account", user_path %></li>
                    <li><%= link_to "Sign Out", signout_path %></li>
                  </ul>
                </li>
              <% else %>
                <a href="#signinModal" role="button" class="btn" data-toggle="modal">Sign In</a>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Dave and Busters</p>
      </footer>

    </div> <!-- /container -->

    <!-- Sign In Modal-->
      <div id="signinModal" class = "modal hide fade" tabindex="-1" role="dialog">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">x</button>
          <h3>Sign In</h3>
        </div>
          <div class="modal-body">
            <ul class="signin_sprites">

              <li>
                  <%= link_to "/auth/facebook", id: "sign_in", :class => "btn btn-large btn-primary" do%>
                    <%= image_tag("facebook-24px.png")%>| Sign in with Facebook  
                  <% end %>
              </li>
              <br>
              <li>
                <%= link_to "/auth/twitter", :class => "btn btn-large btn-primary" do%>
                  <%= image_tag("twitter-bird-light-bgs.png", :id => "twitter_sprite")%> | Sign in with Twitter
                <%end%>
              </li>
            </ul>
          </div>
        
      </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/user/account.html.erb
<h1>User#account</h1>
<p>Find me in app/views/user/account.html.erb</p>